extends Node

enum ROOM_TYPES {VOID=0, PASSAGEWAY=1, ROOM=2}
enum DOOR_TYPES {NORMAL=0, SECRET=1}
enum DOOR_STATUS {CLOSED=0, OPENED=1}

enum DIRECTIONS_VALUE { 
	NONE=0,
	NORTH=1,
	EAST=2,
	SOUTH=4,
	WEST=8,
	NORTH_EAST=NORTH|EAST,
	SOUTH_EAST=SOUTH|EAST,
	NORTH_WEST=NORTH|WEST,
	SOUTH_WEST=SOUTH|WEST
}

const BASE_DIRECTIONS:Array = [
	DIRECTIONS_VALUE.NORTH,
	DIRECTIONS_VALUE.EAST,
	DIRECTIONS_VALUE.SOUTH,
	DIRECTIONS_VALUE.WEST
]

const DIRECTIONS_VECTORS:Dictionary = { 
	DIRECTIONS_VALUE.NORTH : Vector2i(0,-1), 
	DIRECTIONS_VALUE.EAST : Vector2i(1,0), 
	DIRECTIONS_VALUE.SOUTH: Vector2i(0,1), 
	DIRECTIONS_VALUE.WEST : Vector2i(-1,0),
	DIRECTIONS_VALUE.NORTH_EAST : Vector2i(1,-1),
	DIRECTIONS_VALUE.SOUTH_EAST : Vector2i(1,1),
	DIRECTIONS_VALUE.NORTH_WEST : Vector2i(-1,-1),
	DIRECTIONS_VALUE.SOUTH_WEST : Vector2i(-1,1),
}

const OPPOSITE_DIRECTIONS:Dictionary = { 
	DIRECTIONS_VALUE.NORTH : Vector2i(0,1), 
	DIRECTIONS_VALUE.EAST : Vector2i(-1,0), 
	DIRECTIONS_VALUE.SOUTH: Vector2i(0,-1), 
	DIRECTIONS_VALUE.WEST : Vector2i(1,0),
	DIRECTIONS_VALUE.NORTH_EAST : Vector2i(-1,1),
	DIRECTIONS_VALUE.SOUTH_EAST : Vector2i(-1,-1),
	DIRECTIONS_VALUE.NORTH_WEST : Vector2i(1,1),
	DIRECTIONS_VALUE.SOUTH_WEST : Vector2i(1,-1),
}
